#######################################################
# 
# huj2.py
# Python implementation of the Class HUJ2
# Generated by Enterprise Architect
# Created on:      11-мар-2017 9:31:08
# Original author: Администратор
# 
#######################################################


class HUJ2:
    def __init__(self):
        self.pizdarok:str = 'pedrillo'
        self.bduk:str = ''
        self.pizdets:str = 'alert'
        self.pizdar:object = None

    def liquidatePizdets(self, pi:dict=55):
        pass

    def insertHuecheck(self, huek:dict):
        pass

    def cancelPizdots(self, puk:str):
        pass

    def removePizdets(self, huj:int):
        pass
