#######################################################
# 
# huj2.py
# Python implementation of the Class HUJ2
# Generated by Enterprise Architect
# Created on:      10-мар-2017 17:10:48
# Original author: Danilin
# 
#######################################################


class HUJ2:
    def __init__(self):


    def insertHuj():
        pass